import { Loader2, CheckCircle2 } from "lucide-react";

interface SectionStatusProps {
  updating?: boolean;
  justUpdated?: boolean;
}

/**
 * Small inline badge that signals when a section (Plan / Summary / Topics) is
 * being regenerated by the AI, then briefly confirms "Updated" afterward.
 */
export function SectionStatus({ updating, justUpdated }: SectionStatusProps) {
  if (updating) {
    return (
      <span className="inline-flex items-center gap-1 px-1.5 py-0.5 text-[10px] font-medium text-indigo-700 bg-indigo-50 border border-indigo-200 rounded">
        <Loader2 size={10} className="animate-spin" />
        Regenerating…
      </span>
    );
  }
  if (justUpdated) {
    return (
      <span className="inline-flex items-center gap-1 px-1.5 py-0.5 text-[10px] font-medium text-emerald-700 bg-emerald-50 border border-emerald-200 rounded transition-opacity">
        <CheckCircle2 size={10} />
        Updated
      </span>
    );
  }
  return null;
}
